AllCops:
  Exclude:
    - vendor/**/*
    - spec/spec_helper.rb
Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/MethodLength:
  Max: 15
Style/FrozenStringLiteralComment:
  Exclude:
    - bin/console
